USE [master]
GO

/****** Object:  Database [HalifaxAmusementPark]    Script Date: 12/2/18 9:05:12 PM ******/
CREATE DATABASE [HalifaxAmusementPark]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HalifaxAmusementPark', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\HalifaxAmusementPark.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HalifaxAmusementPark_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\HalifaxAmusementPark_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [HalifaxAmusementPark] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HalifaxAmusementPark].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HalifaxAmusementPark] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HalifaxAmusementPark] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HalifaxAmusementPark] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HalifaxAmusementPark] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HalifaxAmusementPark] SET ARITHABORT OFF 
GO

ALTER DATABASE [HalifaxAmusementPark] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HalifaxAmusementPark] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HalifaxAmusementPark] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HalifaxAmusementPark] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HalifaxAmusementPark] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HalifaxAmusementPark] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HalifaxAmusementPark] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HalifaxAmusementPark] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HalifaxAmusementPark] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HalifaxAmusementPark] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HalifaxAmusementPark] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HalifaxAmusementPark] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HalifaxAmusementPark] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HalifaxAmusementPark] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HalifaxAmusementPark] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HalifaxAmusementPark] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HalifaxAmusementPark] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HalifaxAmusementPark] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HalifaxAmusementPark] SET  MULTI_USER 
GO

ALTER DATABASE [HalifaxAmusementPark] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HalifaxAmusementPark] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HalifaxAmusementPark] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HalifaxAmusementPark] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [HalifaxAmusementPark] SET  READ_WRITE 
GO

